ODRIVE_SERVICE_API_LIST = [
    "1. Initialize Odrive",
    "2. Request States",
    "3. Control Modes",
    "4. Position Control"
]
REQUEST_STATE_LIST=[
    # ODrive.Axis.AxisState
"AXIS_STATE_UNDEFINED                         = 0",
"AXIS_STATE_IDLE                              = 1",
"AXIS_STATE_STARTUP_SEQUENCE                  = 2",
"AXIS_STATE_FULL_CALIBRATION_SEQUENCE         = 3",
"AXIS_STATE_MOTOR_CALIBRATION                 = 4",
"AXIS_STATE_ENCODER_INDEX_SEARCH              = 6",
"AXIS_STATE_ENCODER_OFFSET_CALIBRATION        = 7",
"AXIS_STATE_CLOSED_LOOP_CONTROL               = 8",
"AXIS_STATE_LOCKIN_SPIN                       = 9",
"AXIS_STATE_ENCODER_DIR_FIND                  = 10",
"AXIS_STATE_HOMING                            = 11",
"AXIS_STATE_ENCODER_HALL_POLARITY_CALIBRATION = 12",
"AXIS_STATE_ENCODER_HALL_PHASE_CALIBRATION    = 13",
]

INPUT_MODES_LIST=[
"INPUT_MODE_INACTIVE     = 0",
"INPUT_MODE_PASSTHROUGH  = 1",
"INPUT_MODE_VEL_RAMP     = 2",
"INPUT_MODE_POS_FILTER   = 3",
"INPUT_MODE_MIX_CHANNELS = 4",
"INPUT_MODE_TRAP_TRAJ    = 5",
"INPUT_MODE_TORQUE_RAMP  = 6",
"INPUT_MODE_MIRROR       = 7",
"INPUT_MODE_TUNING       = 8",
]

CONTROL_MODES_LIST = [
    "CONTROL_MODE_VOLTAGE_CONTROL  = 0"
    "CONTROL_MODE_TORQUE_CONTROL   = 1"
    "CONTROL_MODE_VELOCITY_CONTROL = 2"
    "CONTROL_MODE_POSITION_CONTROL = 3"
]
